### PR TITLE
fix: add validation for resource group in a case existing SM CRN is not set

### PR DESCRIPTION
**Pull request by akocbek**
### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — CHANGES_REQUESTED** [review]
hmm, interesting use case. Because `resource_group_name` has no default value, it is marked as a required variable. However its not actually required if using existing SM instance. So wondering if we should give `resource_group_name` a default value of `null` but force it to show in required list in `ibm_catalog.json`? Or maybe we leave it as is, but it would force consumers of existing instance to explicably set `resource_group_name` to `null`? Open to suggestions @akocbek @vburckhardt 

Also @akocbek your going to want to add a count around the resource group creation. If passing an existing instance, you don't even want to call the resource group module

**Comment by akocbek** [comment]
```
"Result": {
│         "errors": [
│             {
│                 "code": "access_forbidden",
│                 "message": "API key validation failed. Error: Could not create IAM service ID using the provided configuration. Verify that the provided API key has the correct permissions. [secrets-manager.03121E]",
│                 "more_info": "https://cloud.ibm.com/apidocs/secrets-manager"
│             }
│         ],
│         "status_code": 403,
│         "trace": "a6a0f442-3235-138b-19c5-193ee382a950"
```

**Pull request merged**
