### PR TITLE
fix: renamed existing variables - resource group  and existing kms guid

### PR DESCRIPTION
**Pull request by imprateeksh**
### Description

To align with similar DA changes, variable `existing_resource_group` was renamed to `use_existing_resource_group` and `existing_kms_guid` to `existing_kms_instance_crn`

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by shemau — DISMISSED** [review]
Based on the equivalent change for [KMS](https://github.com/terraform-ibm-modules/terraform-ibm-kms-all-inclusive/pull/454/files) this LGTM

**Comment by alex-reiff** [comment]
If the changes already got covered in https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/pull/101 can this be closed?

**Comment by imprateeksh** [comment]
Sure. @alex-reiff 
The changes are already included. Hence closing the PR.

**Pull request closed without merging**
