### PR TITLE
fix: remove upper limit for required terraform version

### PR DESCRIPTION
**Pull request by akocbek**

### CODE REVIEW

**Comment by ocofaigh** [comment]
Hmm, @alex-reiff seeing this error:
```
2024/06/12 10:45:10 Terraform apply | Error: CreateSecretGroupWithContext failed Not Found
 2024/06/12 10:45:10 Terraform apply | {
 2024/06/12 10:45:10 Terraform apply |     "StatusCode": 404,
 2024/06/12 10:45:10 Terraform apply |     "Headers": {
 2024/06/12 10:45:10 Terraform apply |         "Date": [
 2024/06/12 10:45:10 Terraform apply |             "Wed, 12 Jun 2024 10:45:05 GMT"
 2024/06/12 10:45:10 Terraform apply |         ],
 2024/06/12 10:45:10 Terraform apply |         "Server": [
 2024/06/12 10:45:10 Terraform apply |             "istio-envoy"
 2024/06/12 10:45:10 Terraform apply |         ]
 2024/06/12 10:45:10 Terraform apply |     },
 2024/06/12 10:45:10 Terraform apply |     "Result": null,
 2024/06/12 10:45:10 Terraform apply |     "RawResult": null
 2024/06/12 10:45:10 Terraform apply | }
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply |   with module.iam_secrets_engine[0].module.secrets_manager_group_acct[0].ibm_sm_secret_group.secret_group,
 2024/06/12 10:45:10 Terraform apply |   on .terraform/modules/iam_secrets_engine.secrets_manager_group_acct/main.tf line 8, in resource "ibm_sm_secret_group" "secret_group":
 2024/06/12 10:45:10 Terraform apply |    8: resource "ibm_sm_secret_group" "secret_group" {
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply | Error: CreateConfigurationWithContext failed Not Found
 2024/06/12 10:45:10 Terraform apply | {
 2024/06/12 10:45:10 Terraform apply |     "StatusCode": 404,
 2024/06/12 10:45:10 Terraform apply |     "Headers": {
 2024/06/12 10:45:10 Terraform apply |         "Date": [
 2024/06/12 10:45:10 Terraform apply |             "Wed, 12 Jun 2024 10:45:07 GMT"
 2024/06/12 10:45:10 Terraform apply |         ],
 2024/06/12 10:45:10 Terraform apply |         "Server": [
 2024/06/12 10:45:10 Terraform apply |             "istio-envoy"
 2024/06/12 10:45:10 Terraform apply |         ]
 2024/06/12 10:45:10 Terraform apply |     },
 2024/06/12 10:45:10 Terraform apply |     "Result": null,
 2024/06/12 10:45:10 Terraform apply |     "RawResult": null
 2024/06/12 10:45:10 Terraform apply | }
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply |   with module.iam_secrets_engine[0].ibm_sm_iam_credentials_configuration.sm_iam_engine_configuration,
 2024/06/12 10:45:10 Terraform apply |   on .terraform/modules/iam_secrets_engine/main.tf line 97, in resource "ibm_sm_iam_credentials_configuration" "sm_iam_engine_configuration":
 2024/06/12 10:45:10 Terraform apply |   97: resource "ibm_sm_iam_credentials_configuration" "sm_iam_engine_configuration" {
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply | Error: CreateConfigurationWithContext failed Not Found
 2024/06/12 10:45:10 Terraform apply | {
 2024/06/12 10:45:10 Terraform apply |     "StatusCode": 404,
 2024/06/12 10:45:10 Terraform apply |     "Headers": {
 2024/06/12 10:45:10 Terraform apply |         "Date": [
 2024/06/12 10:45:10 Terraform apply |             "Wed, 12 Jun 2024 10:45:05 GMT"
 2024/06/12 10:45:10 Terraform apply |         ],
 2024/06/12 10:45:10 Terraform apply |         "Server": [
 2024/06/12 10:45:10 Terraform apply |             "istio-envoy"
 2024/06/12 10:45:10 Terraform apply |         ]
 2024/06/12 10:45:10 Terraform apply |     },
 2024/06/12 10:45:10 Terraform apply |     "Result": null,
 2024/06/12 10:45:10 Terraform apply |     "RawResult": null
 2024/06/12 10:45:10 Terraform apply | }
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply |   with module.private_secret_engine[0].ibm_sm_private_certificate_configuration_root_ca.private_certificate_root_ca,
 2024/06/12 10:45:10 Terraform apply |   on .terraform/modules/private_secret_engine/main.tf line 5, in resource "ibm_sm_private_certificate_configuration_root_ca" "private_certificate_root_ca":
 2024/06/12 10:45:10 Terraform apply |    5: resource "ibm_sm_private_certificate_configuration_root_ca" "private_certificate_root_ca" {
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply | Error: CreateConfigurationWithContext failed Not Found
 2024/06/12 10:45:10 Terraform apply | {
 2024/06/12 10:45:10 Terraform apply |     "StatusCode": 404,
 2024/06/12 10:45:10 Terraform apply |     "Headers": {
 2024/06/12 10:45:10 Terraform apply |         "Date": [
 2024/06/12 10:45:10 Terraform apply |             "Wed, 12 Jun 2024 10:45:05 GMT"
 2024/06/12 10:45:10 Terraform apply |         ],
 2024/06/12 10:45:10 Terraform apply |         "Server": [
 2024/06/12 10:45:10 Terraform apply |             "istio-envoy"
 2024/06/12 10:45:10 Terraform apply |         ]
 2024/06/12 10:45:10 Terraform apply |     },
 2024/06/12 10:45:10 Terraform apply |     "Result": null,
 2024/06/12 10:45:10 Terraform apply |     "RawResult": null
 2024/06/12 10:45:10 Terraform apply | }
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply |   with module.secrets_manager_public_cert_engine[0].ibm_sm_public_certificate_configuration_dns_cis.public_dns_config[0],
 2024/06/12 10:45:10 Terraform apply |   on .terraform/modules/secrets_manager_public_cert_engine/main.tf line 75, in resource "ibm_sm_public_certificate_configuration_dns_cis" "public_dns_config":
 2024/06/12 10:45:10 Terraform apply |   75: resource "ibm_sm_public_certificate_configuration_dns_cis" "public_dns_config" {
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply | Error: CreateConfigurationWithContext failed Not Found
 2024/06/12 10:45:10 Terraform apply | {
 2024/06/12 10:45:10 Terraform apply |     "StatusCode": 404,
 2024/06/12 10:45:10 Terraform apply |     "Headers": {
 2024/06/12 10:45:10 Terraform apply |         "Date": [
 2024/06/12 10:45:10 Terraform apply |             "Wed, 12 Jun 2024 10:45:05 GMT"
 2024/06/12 10:45:10 Terraform apply |         ],
 2024/06/12 10:45:10 Terraform apply |         "Server": [
 2024/06/12 10:45:10 Terraform apply |             "istio-envoy"
 2024/06/12 10:45:10 Terraform apply |         ]
 2024/06/12 10:45:10 Terraform apply |     },
 2024/06/12 10:45:10 Terraform apply |     "Result": null,
 2024/06/12 10:45:10 Terraform apply |     "RawResult": null
 2024/06/12 10:45:10 Terraform apply | }
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply | 
 2024/06/12 10:45:10 Terraform apply |   with module.secrets_manager_public_cert_engine[0].ibm_sm_public_certificate_configuration_ca_lets_encrypt.public_ca_config[0],
 2024/06/12 10:45:10 Terraform apply |   on .terraform/modules/secrets_manager_public_cert_engine/main.tf line 99, in resource "ibm_sm_public_certificate_configuration_ca_lets_encrypt" "public_ca_config":
 2024/06/12 10:45:10 Terraform apply |   99: resource "ibm_sm_public_certificate_configuration_ca_lets_encrypt" "public_ca_config" {
```

Any ideas?

**Comment by alex-reiff** [comment]
@ocofaigh Could that possibly be connected to the ongoing inc7282048? Never seen it 404 like that, especially bringing up istio out of nowhere.

**Comment by alex-reiff** [comment]
Well the 404s disappeared but now it's:
```
=== NAME  TestRunDASolutionSchematics
    schematics.go:491: [SCHEMATICS] ... still waiting for job APPLY to complete: 8 minutes
    schematics.go:491: [SCHEMATICS] ... still waiting for job APPLY to complete: 9 minutes
    schematics.go:491: [SCHEMATICS] ... still waiting for job APPLY to complete: 10 minutes
    schematics.go:491: [SCHEMATICS] ... still waiting for job APPLY to complete: 11 minutes
    schematics.go:491: [SCHEMATICS] ... still waiting for job APPLY to complete: 12 minutes
    schematics.go:491: [SCHEMATICS] ... still waiting for job APPLY to complete: 13 minutes
    schematics.go:491: [SCHEMATICS] ... still waiting for job APPLY to complete: 14 minutes
    schematics.go:500: [SCHEMATICS] The status of job APPLY is: FAILED
    tests.go:141: 
        	Error Trace:	/go/pkg/mod/github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper@v1.33.2/testschematic/tests.go:141
        	            				/__w/terraform-ibm-secrets-manager/terraform-ibm-secrets-manager/tests/pr_test.go:121
        	Error:      	Not equal: 
        	            	expected: "COMPLETED"
        	            	actual  : "FAILED"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-COMPLETED
        	            	+FAILED
        	Test:       	TestRunDASolutionSchematics
        	Messages:   	APPLY has failed with status FAILED - [ sm-da-ushbff (us-south.workspace.sm-da-ushbff.fb5dc0de) ]
    tests.go:156: [SCHEMATICS] Starting DESTROY job ...
    schematics.go:491: [SCHEMATICS] ... still waiting for job DESTROY to complete: 1 minutes
    schematics.go:491: [SCHEMATICS] ... still waiting for job DESTROY to complete: 2 minutes
    schematics.go:500: [SCHEMATICS] The status of job DESTROY is: COMPLETED
--- FAIL: TestRunDASolutionSchematics (1158.54s)
```

**Pull request merged**
