### PR TITLE
fix: clarify KMS encryption in solution

### PR DESCRIPTION
**Pull request by shemau**
### Description

Ref: #74 

Clarify KMS properties under standard solution

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by shemau** [comment]
Whilst reviewing, please provide feedback on the unchanged default values for the kms_key_ring_name and kms_key_name fields.

**Comment by shemau** [comment]
Additional issues were identified and fixed:
Spurious reference to COS in a comment was corrected.
Incorrect reference to skip_kms_iam_authorization_policy was corrected.

**Review by alex-reiff — APPROVED** [review]

**Review by ocofaigh — COMMENTED** [review]
Some of these issues were being addressed in https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/pull/68 - but I'm going to merge this PR as its ready to go (FYI @tyao117 )

**Pull request merged**
